export const feedUrls = [
    { name: 'Assam', url: 'https://www.hindusthansamachar.in/Regional/HASM/HASM.rss' },
    { name: 'Bihar', url: 'https://www.hindusthansamachar.in/Regional/HBIH/HBIH.rss' },
    { name: 'Chhattisgarh', url: 'https://www.hindusthansamachar.in/Regional/HCTG/HCTG.rss' },
    { name: 'Delhi', url: 'https://www.hindusthansamachar.in/Regional/HGON/HGON.rss' },
    { name: 'Gujarat', url: 'https://www.hindusthansamachar.in/Regional/HGUJ/HGUJ.rss' },
    { name: 'Haryana', url: 'https://www.hindusthansamachar.in/Regional/HHAR/HHAR.rss' },
    { name: 'Himachal Pradesh', url: 'https://www.hindusthansamachar.in/Regional/HHIM/HHIM.rss' },
    { name: 'Jammu & Kashmir', url: 'https://www.hindusthansamachar.in/Regional/HJAK/HJAK.rss' },
    { name: 'Jharkhand', url: 'https://www.hindusthansamachar.in/Regional/HJHA/HJHA.rss' },
    { name: 'Karnataka', url: 'https://www.hindusthansamachar.in/Regional/HKAR/HKAR.rss'},
    { name: 'Madhya Pradesh', url: 'https://www.hindusthansamachar.in/Regional/HMAD/HMAD.rss'},
    { name: 'Maharashtra', url: 'https://www.hindusthansamachar.in/Regional/HMAH/HMAH.rss'},
    { name: 'Punjab', url: 'https://www.hindusthansamachar.in/Regional/HPUN/HPUN.rss'},
    { name: 'Rajasthan', url: 'https://www.hindusthansamachar.in/Regional/HRAJ/HRAJ.rss'},
    { name: 'Sikkim', url: 'https://www.hindusthansamachar.in/Regional/HSIK/HSIK.rss'},
    { name: 'Uttarakhand', url: 'https://www.hindusthansamachar.in/Regional/HUKD/HUKD.rss'},
    { name: 'Uttar Pradesh', url: 'https://www.hindusthansamachar.in/Regional/HUPR/HUPR.rss'},
    { name: 'West Bengal', url: 'https://www.hindusthansamachar.in/Regional/HWBL/HWBL.rss'},
    { name: 'Agri science tech', url: 'https://www.hindusthansamachar.in/HAST/HAST.rss'},
    { name: 'Breaking', url: 'https://www.hindusthansamachar.in/HBRE/HBRE.rss'},
    { name: 'Business', url: 'https://www.hindusthansamachar.in/HBUS/HBUS.rss'},
    { name: 'Crime', url: 'https://www.hindusthansamachar.in/HCRI/HCRI.rss'},
    { name: 'Entertainment', url: 'https://www.hindusthansamachar.in/HENT/HENT.rss'},
    { name: 'International', url: 'https://www.hindusthansamachar.in/HINT/HINT.rss'},
    { name: 'National', url: 'https://www.hindusthansamachar.in/HNAT/HNAT.rss'},
    { name: 'Ram Janambhoomi', url: 'https://www.hindusthansamachar.in/HRJB/HRJB.rss'},
    { name: 'Article', url: 'https://www.hindusthansamachar.in/HRTL/HRTL.rss'},
    { name: 'Special News / Lok Ruchi', url: 'https://www.hindusthansamachar.in/HSNL/HSNL.rss'},
    { name: 'Sports', url: 'https://www.hindusthansamachar.in/HSPO/HSPO.rss'},
]